version: '3.8'

services:
  postgres_dev:
    image: postgres:15
    container_name: postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bot_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis_dev:
    image: redis:7
    container_name: redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bot_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bot_dev
    env_file:
      - .env.dev
    environment:
      ENV_PATH: .env.dev
      PYTHONPATH: /app
    ports:
      - "8080:8080"  # Пробрасываем порт для webhook
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Доступ к хосту из контейнера
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - dev_network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  dev_network:
    driver: bridge
