  services:
    db:
      image: postgres:15
      container_name: ${DB_CONTAINER_NAME}
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5433:5432"  # Изменяем порт для Windows
      volumes:
        - postgres_data_april_bot:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        timeout: 5s
        retries: 5

    redis:
      image: redis:7
      container_name: april_test_redis
      ports:
        - "6379:6379"  # Открываем Redis-порт
      restart: unless-stopped
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 10s
        timeout: 5s
        retries: 5

    bot:
      build: .
      container_name: ${BOT_CONTAINER_NAME}
      env_file:
        - .env
      environment:
        ENV_PATH: .env
        PYTHONPATH: /app  # This makes Python look for modules in /app
        USE_WEBHOOK: "true"  # Явно указываем webhook режим
      ports:
        - "8080:8080"  # Пробрасываем порт для webhook
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy
      volumes:
        - .:/app
      command: >
        sh -c "while ! nc -z db 5432; do sleep 1; done &&
        while ! nc -z redis 6379; do sleep 1; done &&
        alembic upgrade head &&
        python -m bot.bot"

  volumes:
    postgres_data_april_bot: