"""init

Revision ID: d62bd1141646
Revises: 
Create Date: 2025-09-16 22:11:57.813423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62bd1141646'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeout_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('added_to_attachment_menu', sa.Boolean(), nullable=True),
    sa.Column('can_join_groups', sa.Boolean(), nullable=True),
    sa.Column('can_read_all_group_messages', sa.Boolean(), nullable=True),
    sa.Column('supports_inline_queries', sa.Boolean(), nullable=True),
    sa.Column('can_connect_to_business', sa.Boolean(), nullable=True),
    sa.Column('has_main_web_app', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('creator_user_id', sa.BigInteger(), nullable=True),
    sa.Column('added_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('bot_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('can_manage_chat', sa.Boolean(), nullable=True),
    sa.Column('can_delete_messages', sa.Boolean(), nullable=True),
    sa.Column('can_restrict_members', sa.Boolean(), nullable=True),
    sa.Column('can_promote_members', sa.Boolean(), nullable=True),
    sa.Column('can_invite_users', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'chat_id', name='uix_bot_chat')
    )
    op.create_index('ix_bot_permissions_bot_chat', 'bot_permissions', ['bot_id', 'chat_id'], unique=False)
    op.create_table('captcha_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('answer', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_chat', 'captcha_answers', ['user_id', 'chat_id'], unique=False)
    op.create_index(op.f('ix_captcha_answers_chat_id'), 'captcha_answers', ['chat_id'], unique=False)
    op.create_index(op.f('ix_captcha_answers_expires_at'), 'captcha_answers', ['expires_at'], unique=False)
    op.create_index(op.f('ix_captcha_answers_user_id'), 'captcha_answers', ['user_id'], unique=False)
    op.create_table('captcha_message_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_chat_msg', 'captcha_message_ids', ['user_id', 'chat_id'], unique=False)
    op.create_index(op.f('ix_captcha_message_ids_chat_id'), 'captcha_message_ids', ['chat_id'], unique=False)
    op.create_index(op.f('ix_captcha_message_ids_expires_at'), 'captcha_message_ids', ['expires_at'], unique=False)
    op.create_index(op.f('ix_captcha_message_ids_user_id'), 'captcha_message_ids', ['user_id'], unique=False)
    op.create_table('captcha_settings',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_visual_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.chat_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('enable_photo_filter', sa.Boolean(), nullable=True),
    sa.Column('admins_bypass_photo_filter', sa.Boolean(), nullable=True),
    sa.Column('photo_filter_mute_minutes', sa.Integer(), nullable=True),
    sa.Column('mute_new_members', sa.Boolean(), nullable=True),
    sa.Column('auto_mute_scammers', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('group_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_creator', sa.Boolean(), nullable=True),
    sa.Column('can_view_admins', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='uix_user_chat')
    )
    op.create_table('scammer_tracker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=True),
    sa.Column('is_scammer', sa.Boolean(), nullable=True),
    sa.Column('scammer_level', sa.Integer(), nullable=True),
    sa.Column('first_violation_at', sa.DateTime(), nullable=True),
    sa.Column('last_violation_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='uix_scammer_user_chat')
    )
    op.create_index('idx_scammer_level', 'scammer_tracker', ['scammer_level'], unique=False)
    op.create_index('idx_scammer_user_chat', 'scammer_tracker', ['user_id', 'chat_id'], unique=False)
    op.create_index('idx_scammer_violation_type', 'scammer_tracker', ['violation_type'], unique=False)
    op.create_index(op.f('ix_scammer_tracker_chat_id'), 'scammer_tracker', ['chat_id'], unique=False)
    op.create_index(op.f('ix_scammer_tracker_user_id'), 'scammer_tracker', ['user_id'], unique=False)
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_group_group_id'), 'user_group', ['group_id'], unique=False)
    op.create_index('ix_user_group_unique', 'user_group', ['user_id', 'group_id'], unique=True)
    op.create_index(op.f('ix_user_group_user_id'), 'user_group', ['user_id'], unique=False)
    op.create_table('user_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('restriction_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_restriction_user_chat', 'user_restrictions', ['user_id', 'chat_id'], unique=False)
    op.create_table('visual_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('answer', sa.String(length=10), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visual_captcha_expires', 'visual_captcha', ['expires_at'], unique=False)
    op.create_index('idx_visual_captcha_user_chat', 'visual_captcha', ['user_id', 'chat_id'], unique=False)
    op.create_index(op.f('ix_visual_captcha_chat_id'), 'visual_captcha', ['chat_id'], unique=False)
    op.create_index(op.f('ix_visual_captcha_expires_at'), 'visual_captcha', ['expires_at'], unique=False)
    op.create_index(op.f('ix_visual_captcha_user_id'), 'visual_captcha', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_captcha_user_id'), table_name='visual_captcha')
    op.drop_index(op.f('ix_visual_captcha_expires_at'), table_name='visual_captcha')
    op.drop_index(op.f('ix_visual_captcha_chat_id'), table_name='visual_captcha')
    op.drop_index('idx_visual_captcha_user_chat', table_name='visual_captcha')
    op.drop_index('idx_visual_captcha_expires', table_name='visual_captcha')
    op.drop_table('visual_captcha')
    op.drop_index('ix_user_restriction_user_chat', table_name='user_restrictions')
    op.drop_table('user_restrictions')
    op.drop_index(op.f('ix_user_group_user_id'), table_name='user_group')
    op.drop_index('ix_user_group_unique', table_name='user_group')
    op.drop_index(op.f('ix_user_group_group_id'), table_name='user_group')
    op.drop_table('user_group')
    op.drop_index(op.f('ix_scammer_tracker_user_id'), table_name='scammer_tracker')
    op.drop_index(op.f('ix_scammer_tracker_chat_id'), table_name='scammer_tracker')
    op.drop_index('idx_scammer_violation_type', table_name='scammer_tracker')
    op.drop_index('idx_scammer_user_chat', table_name='scammer_tracker')
    op.drop_index('idx_scammer_level', table_name='scammer_tracker')
    op.drop_table('scammer_tracker')
    op.drop_table('group_users')
    op.drop_table('chat_settings')
    op.drop_table('captcha_settings')
    op.drop_index(op.f('ix_captcha_message_ids_user_id'), table_name='captcha_message_ids')
    op.drop_index(op.f('ix_captcha_message_ids_expires_at'), table_name='captcha_message_ids')
    op.drop_index(op.f('ix_captcha_message_ids_chat_id'), table_name='captcha_message_ids')
    op.drop_index('idx_user_chat_msg', table_name='captcha_message_ids')
    op.drop_table('captcha_message_ids')
    op.drop_index(op.f('ix_captcha_answers_user_id'), table_name='captcha_answers')
    op.drop_index(op.f('ix_captcha_answers_expires_at'), table_name='captcha_answers')
    op.drop_index(op.f('ix_captcha_answers_chat_id'), table_name='captcha_answers')
    op.drop_index('idx_user_chat', table_name='captcha_answers')
    op.drop_table('captcha_answers')
    op.drop_index('ix_bot_permissions_bot_chat', table_name='bot_permissions')
    op.drop_table('bot_permissions')
    op.drop_table('groups')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('timeout_messages')
    # ### end Alembic commands ###
