"""add_global_mute_enabled

Revision ID: df251fa0997f
Revises: d62bd1141646
Create Date: 2025-10-18 20:13:22.380157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df251fa0997f'
down_revision: Union[str, None] = 'd62bd1141646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_settings', sa.Column('global_mute_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_settings', 'global_mute_enabled')
    # ### end Alembic commands ###
